src/Entity/Changes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChangesRepository")
 */
class Changes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $change_id;

    /**
     * @ORM\Column(type="text")
     */
    private $name;


    public function getChangeId(): ?int
    {
        return $this->change_id;
    }

    public function setChangeId(int $change_id): self
    {
        $this->change_id = $change_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Controller/ChangeController.php
<?php
namespace App\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Entity\Changes;
use App\Entity\ChangesSiteChanges;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class ChangeController extends AbstractController { 

    /** 
     * @Route("/changes", name="changes")
     * 
    */
    function viewAllChanges(SessionInterface $session) {
        if($session->get('account') !== null) {
            if(isset($_POST['change'])) {
                $change = new Changes();
                $change->setName($_POST['change']);
                $db = $this->getDoctrine()->getManager();
                $db->persist($change);
                $db->flush();
            }
            $changes = $this->getDoctrine()->getRepository(Changes::class)->findAll();
            return $this->render("Change/changes.html.twig", ["changes" => $changes]);
        } else {
            return $this->redirectToRoute("login");
        }
    }

    /** 
     * 
     * @Route("/changes/delete/{id}", name="deleteChange")
    */
    function deleteChange(SessionInterface $session, $id) {
        if($session !== null) {
            $change1 = $this->getDoctrine()->getRepository(ChangesSiteChanges::class)->findBy(["change_id" => $id]);
            $db1 = $this->getDoctrine()->getManager();
            foreach($change1 as $change) {

                $db1->remove($change);

            }
            $change = $this->getDOctrine()->getRepository(Changes::class)->find($id);
            $db = $this->getDoctrine()->getManager();
            $db->remove($change);
            $db->flush();
            return $this->redirectToRoute("changes");
        } else {
            return $this->redirectToRoute("login");
        }
    }

}

templates/Change/changes.html.twig
{% extends "base.html.twig" %}
{% block body %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="/sites">Strony</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="/changes">Zamiany</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/logout">Wyloguj</a>
  </li>
</ul>
<br><br>
<center><h1>Lista możliwych zmian</h1></center>
<br><br>
<center>
<form method="post">
<label for="name">Dodaj: 
<input type="text" name="change" /> </label>
<input type="submit" name="submit" value="Dodaj" />
</form> 
    <table class="table table-striped" style="width: 75%;">
        <thead class="thead-light">
            <tr>
                <td><strong>Zmiana:</strong></td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>    
    {% for  change in changes %}
        <tr>
            <td>{{ change.name }}</td>
            <td><a href="/changes/delete/{{ change.changeId }}">Kasuj</a></td>
        </tr>    
    {% endfor %}
    </tbody>
</table>
</center>
{% endblock %}